[workspace]
members = [ "crates/*" ]
default-members = [ "crates/web" ]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0 OR MIT"
version = "0.2.0-pre"

[workspace.dependencies]
rayon = "1.8.0"
serde =  "1.0.193"
serde_json = "1.0.108"
utoipa = "4.1.0"
