[package]
name = "wildbg-c"

version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "wildbg"
crate-type = ["staticlib"]

[dependencies]
# internal
engine = { path = "../engine" }
logic = { path = "../logic" }
